# permissions for end users to view grafanacloudlogforwarders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafanacloudlogforwarder-viewer-role
rules:
- apiGroups:
  - grafana.example.com
  resources:
  - grafanacloudlogforwarders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - grafana.example.com
  resources:
  - grafanacloudlogforwarders/status
  verbs:
  - get
